In [9]:
import numpy as np

a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int64)
c = np.ones((2,3), dtype = np.int16)
d = a +b+c
print(d[1,2])

print(d)

5
[[2 3 4]
 [1 2 5]]


In [10]:
import numpy as np
a= np.array([[0,1,0],[1,0,1]])
a+=3
b = a+3
print(a[1,2] +b[1,2])

11


In [ ]:
import numpy as np
a = np.array([[3,6,7],[5,-3,0]])
b= np.array([[1,1],[2,1],[3,-4]])
c = mp.dot(a,b)
print(c)

In [12]:
import numpy as np

# Tạo một mảng 5 chiều có kích thước (2, 3, 4, 5, 3)
arr_5d = np.zeros((2, 1, 2, 5, 3))
print(arr_5d)


[[[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



 [[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]]


In [14]:
import numpy as np

# Định nghĩa hai vector
v1 = np.array([1, 2, 3, 4])
print(v1+1)
v2 = np.array([5, 6, 7, 8])
print(v1*v2)

[2 3 4 5]
[ 5 12 21 32]
